plugins {
    id 'org.springframework.boot' version '2.6.3'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
   // id "io.freefair.lombok" version "6.3.0"
    id "com.netflix.dgs.codegen" version "5.1.16"
    id 'java'
    id 'idea'
    id 'com.bmuschko.docker-remote-api' version '6.7.0'
    id 'com.bmuschko.docker-java-application' version '7.3.0'

}


docker {
    javaApplication {
        baseImage = 'bitnami/java:17.0.2'
        maintainer = 'Nadav Babai  "nadavbabai@outllok.com"'
        ports = [8080]
        images = ['awesome-spring-boot:1.115', 'awesome-spring-boot:latest']
        jvmArgs = [ '-Xmx2048m']
    }
}


group = 'com.shaked.service'
sourceCompatibility = '17'


generateJava {
    // packageName and subPackageNameTypes are set to generate correct union | interfaces
    packageName = "com.shaked.service"
    subPackageNameTypes = "models" // Workaround Relay Node interface support for Json deserialization
    generateClient = false
    typeMapping = [
            "Service"      : "com.shaked.service.models.Service",
            "Article"      : "com.shaked.service.models.Article",
            "Answer"       : "com.shaked.service.models.Answer",
            "Contact"      : "com.shaked.service.models.Contact",
            "Survey"       : "com.shaked.service.models.Survey",
            "TextContainer": "com.shaked.service.models.TextContainer",

    ]
}


repositories {
    mavenCentral()
}


dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation 'org.springframework.security:spring-security-core:5.5.1'
    implementation 'org.springframework.security:spring-security-config:5.5.1'

    //GraphQL
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:latest.release"))
    implementation 'com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter'
    implementation 'com.netflix.graphql.dgs:graphql-dgs-pagination'
    implementation 'com.graphql-java:graphql-java-extended-scalars'


    compileOnly 'org.projectlombok:lombok:1.18.22'
    annotationProcessor 'org.projectlombok:lombok:1.18.22'

    testCompileOnly 'org.projectlombok:lombok:1.18.22'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.22'

    runtimeOnly 'mysql:mysql-connector-java'
    // annotationProcessor 'org.projectlombok:lombok'

    // Unit TESTS
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'

}

test {
    useJUnitPlatform()
}
