scalar Date
scalar Upload

type Query {
    module(where: ModuleUniqueInput!):Module
    modules(where: ModuleWhereInput):[Module]
    contact(where:ContactUniqueInput!):Contact
    contacts:[Contact]
    media:[Media]
    isAuthenticated: Boolean

}

type Mutation {
    saveContact(data:ContactInput!):Contact
    deleteContact(id:ID!):Contact!
    saveModule(data:ModuleInput!):Module
    deleteModule(id:ID!):Module!
    deleteMedia(id:ID!):Module!

}
extend type Mutation  {
    saveMedia(data:Upload!):Media
}


type Media {
    id:ID!
    fileName:String
    createdAt: Date!
    updatedAt: Date!
}

input ModuleUniqueInput {
    id:String!
}

input ModuleWhereInput {
    type:ModuleType
}


input ContactUniqueInput {
    id:String!
}
type Module {
    id:ID!
    title:String
    tag:String
    introduction:String
    content:String
    contactButton:String
    createdAt: Date!
    updatedAt: Date!
    mediaId:Int
    type:ModuleType!
}

type Contact {
    id:ID!
    fullName:String!
    phoneNumber: String!
    email: String
    address: String
    category: String
    createdAt: Date!
    survey: Survey
    comment:String
}

type Survey {
    id:ID
    name:String
    answers:[Answer]
}

type Answer {
    id:ID
    question: String
    answer: String
}


input ContactInput {
    fullName:String!
    phoneNumber: String!
    email: String
    address: String
    category: String
    survey: SurveyInput
}

input SurveyInput{
    name:String
    answers:[AnswerInput]
}

input AnswerInput {
    question: String
    answer: String
}

input ModuleInput {
    id: ID
    title: String
    introduction: String
    tag: String
    content:String
    contactButton: String
    mediaId: Int
    type: ModuleType
}


enum ModuleType {
    ARTICLE,
    OFFER,
    INTRODUCTION,
    SERVICE
}



