scalar Date
scalar Long
scalar Upload

type Query {
    service(id: ID!):Service
    services:[Service]
    article(id: ID!):Article
    articles:[Article]
    text(id:ID!): TextContainer
    texts: [TextContainer]
    contact(id:ID!):Contact
    contacts:[Contact]
    media:[Media]
}

type Mutation {
    createContact(contactInput:ContactInput!):Contact
    deleteContact(id:ID!):ID!
    saveArticle(data:ArticleInput!):Article
    deleteArticle(id:ID!):ID!
}
extend type Mutation  {
    saveMedia(data:Upload!):Media
}


type Media {
    id:Long
    fileName:String
}

type Service {
    id:Long!
    title:String
    introduction:String
    content:String
    contactButton:String
}

type Article {
    id:ID!
    title:String
    tag:String
    introduction:String
    content:String
    contactButton:String
    modificationDate: Date
}

type Contact {
    id:ID!
    fullName:String
    phoneNumber: String
    email: String
    address: String
    category: String
    date: Date
    survey: Survey
    comment:String
}

type Survey {
    id:ID
    name:String
    answers:[Answer]
}

type Answer {
    id:ID
    question: String
    answer: String
}

type TextContainer {
    id:ID!
    tag:String
    content:String
}


input ContactInput {
    fullName:String
    phoneNumber: String
    email: String
    address: String
    category: String
    survey: SurveyInput
}

input SurveyInput{
    name:String
    answers:[AnswerInput]
}

input AnswerInput {
    question: String
    answer: String
}

input ArticleInput {
    id: ID
    title: String
    introduction: String
    tag: String
    content:String
    contactButton: String
}
